global:
  scrape_interval: 15s
  evaluation_interval: 15s

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

rule_files:
  - "alert_rules.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'excel_api'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['excel_api:8080']

  - job_name: 'excel_frontend'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['excel_frontend:3000']

  - job_name: 'excel_database'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['excel_database:5432']

  - job_name: 'node_exporter'
    static_configs:
      - targets: ['node_exporter:9100']

# Human tasks:
# TODO: Review and adjust scrape intervals and evaluation intervals based on specific monitoring requirements
# TODO: Verify and update target hostnames and ports for each job to match the actual deployment configuration
# TODO: Create and configure alert_rules.yml file referenced in the rule_files section