apiVersion: v1
kind: Secret
metadata:
  name: excel-secrets
  namespace: excel-namespace
type: Opaque
data:
  DB_CONNECTION_STRING: <base64_encoded_connection_string>
  API_KEY: <base64_encoded_api_key>
  AZURE_STORAGE_ACCOUNT_KEY: <base64_encoded_storage_account_key>
  JWT_SECRET: <base64_encoded_jwt_secret>

# Human Tasks:
# - Generate and encode actual secret values for production use (Critical)
# - Ensure secrets are properly managed and rotated according to security policies (Required)
# - Implement proper RBAC (Role-Based Access Control) for accessing these secrets (Required)